name: Xplat Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          7.x
    - name: Install RocksDB Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsnappy-dev libc6-dev librocksdb-dev -y
    - name: Build and Test
      run: |
        dotnet restore --verbosity normal
        dotnet build --no-restore --verbosity normal
        dotnet test --no-build --verbosity normal
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./test/**/neo-coverage.cobertura.xml
